######################################################################
# Automatically generated by qmake (3.0) Thu May 1 12:16:36 2014
######################################################################

QT+= gui opengl
TEMPLATE = app
TARGET = LEDCubeFinal
INCLUDEPATH += .

# Input
HEADERS += myglwidget.h window.h
SOURCES += main.cpp myglwidget.cpp window.cpp
